baseurl = "https://lunelune-alpine.netlify.app"
title = "お山登りるんるん会"
languageCode = "ja"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable Disqus comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
staticDir = ["static", "static/img"] # "static/img" for images
hasCJKLanguage = true # 日本語・中国語・韓国語の単語カウントを有効にする
summaryLength = 120 # サマリーの長さを120単語にする

[menu]
  # Sets the menu items in the navigation bar
  # Identifier prepends a Font Awesome icon to the menu item
  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5
    
  [[menu.main]]
    name              = "Members"
    identifier        = "members"
    url               = "/members/"
    pre               = "<i class='fas fa-hiking'></i>"
    weight            = 6

  [[menu.main]]
    name              = "Admin"
    identifier        = "admin"
    url               = "/admin/"
    pre               = "<i class='fas fa-user-circle'></i>"
    weight            = 9

  [[menu.main]]
    name              = "Calendar"
    identifier        = "calendar"
    url               = "https://calendar.google.com/calendar/b/2?cid=bHVuZWx1bmUuYWxwaW5lQGdtYWlsLmNvbQ"
    pre               = "<i class='far fa-calendar-alt'></i>"
    weight            = 7
[Params]
  subtitle = "戸山高校山岳部OB・OG交流の場" # Subtitle of your site. Used in site header
  description = "" # Site description. Used in meta description
  copyright = "お山登りるんるん会" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["date", "author", "categories", "translations"] # Order of post meta information
  mainSections = ["blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  highlightColor = "#008080" # Override highlight color
  customCSS = ["css/custom.css"] # Include custom CSS files
  customJS = ["js/custom.js"] # Include custom JS files
  
[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
        # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  facebook = "username"
  twitter = "username"
  instagram = "username"
  email = "lunelune.alpine@gmail.com"

# Custom social links
[[Params.widgets.social.custom]]
  title = "Youtube"
  url = "https://youtube.com/user/username"
      #icon = "youtube.svg" # Optional. Path relative to "layouts/partials"

#[[Params.widgets.social.custom]]
#  title = "website you want to link"
#  url = "https://link_url.example"