backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
locale: 'ja'
media_folder: "site/static/img" # Media files will be stored in the repo under img/
public_folder: "/img"
publish_mode: editorial_workflow
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "site/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Categories",  name: "categories", widget: "relation", collection: "categories", searchFields: ["title"], valueField: "title", displayFields: ["title"]}
      - {label: "Tags", name: "tags", widget: "relation", required: false, collection: "tags", searchFields: ["title"], valueField: "title", displayFields: ["title"], multiple: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "categories"
    label: "categories"
    folder: "site/content/categories"
    create: true
    fields:
      - { label: "CategoryNames", name: "title", widget: "string"}
  - name: "tags"
    label: "tags"
    folder: "site/content/tags"
    create: true
    fields:
      - { label: "TagNames", name: "title", widget: "string"}
      